#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use PicoFeed\Config\Config;
use PicoFeed\Parser\Feed;
use PicoFeed\Reader\Favicon;
use PicoFeed\Scraper\Scraper;
use PicoFeed\Reader\Reader;
use PicoFeed\Logging\Logger;
use PicoFeed\PicoFeedException;


if (class_exists('\Monolog\Logger')) {
    $log = new \Monolog\Logger('log');
    $handler = new Monolog\Handler\StreamHandler('debug.log', \Monolog\Logger::DEBUG);
    $log->pushHandler($handler);
    Logger::setLogger($log);
    printf("Monolog found, logs will be written in debug.log.\n");
} else {
    printf("Monolog is not installed, we won't log anything.\n");
}

function get_feed($url, $disable_filtering = false)
{
    try {

        $reader = new Reader;
        $resource = $reader->discover($url);

        $parser = $reader->getParser(
            $resource->getUrl(),
            $resource->getContent(),
            $resource->getEncoding()
        );

        if ($disable_filtering) {
            $parser->disableContentFiltering();
        }

        return $parser->execute();
    }
    catch (PicoFeedException $e) {
        echo 'Exception thrown ===> "'.$e->getMessage().'"'.PHP_EOL;
        return false;
    }
}

function get_item(Feed $feed, $item_id)
{
    foreach ($feed->items as $item) {
        if ($item->getId() === $item_id) {
            echo $item;
            echo "============= CONTENT ================\n";
            echo $item->getContent();
            echo "\n============= CONTENT ================\n";
            break;
        }
    }
}

function dump_feed($url)
{
    $feed = get_feed($url);
    echo $feed;
}

function dump_item($url, $item_id)
{
    $feed = get_feed($url);

    if ($feed !== false) {
        get_item($feed, $item_id);
    }
}

function nofilter_item($url, $item_id)
{
    $feed = get_feed($url, true);

    if ($feed !== false) {
        get_item($feed, $item_id);
    }
}

function grabber($url)
{
    $grabber = new Scraper(new Config);
    $grabber->setUrl($url);
    $grabber->execute();

//    print_r(Logger::getMessages());
    echo "============= CONTENT ================\n";
    echo $grabber->getRelevantContent().PHP_EOL;
    echo "============= FILTERED ================\n";
    echo $grabber->getFilteredContent().PHP_EOL;
}

function fetch_favicon($url)
{
    $favicon = new Favicon();
    echo $favicon->find($url) . PHP_EOL;
}

// Parse command line arguments
if ($argc === 4) {
    switch ($argv[1]) {
        case 'item':
            dump_item($argv[2], $argv[3]);
            die;
        case 'nofilter':
            nofilter_item($argv[2], $argv[3]);
            die;
    }
} else if ($argc === 3) {
    switch ($argv[1]) {
        case 'feed':
            dump_feed($argv[2]);
            die;
        case 'grabber':
            grabber($argv[2]);
            die;
        case 'favicon':
            fetch_favicon($argv[2]);
            die;
    }
}

printf("Usage:\n");
printf("%s feed <feed-url>\n", $argv[0]);
printf("%s item <feed-url> <item-id>\n", $argv[0]);
printf("%s nofilter <feed-url> <item-id>\n", $argv[0]);
printf("%s grabber <url>\n", $argv[0]);
printf("%s favicon <url>\n", $argv[0]);
